import type { MeasurementUnit } from '../types/common';

export const SAMPLE_INGREDIENTS = [
  { label: 'San Marzano Tomatoes', value: 'san-marzano-tomatoes' },
  { label: 'Olive Oil', value: 'olive-oil' },
  { label: 'Garlic', value: 'garlic' },
  { label: 'Onion', value: 'onion' },
  { label: 'Salt', value: 'salt' },
  { label: 'Black Pepper', value: 'black-pepper' },
  { label: 'Flour', value: 'flour' },
  { label: 'Sugar', value: 'sugar' },
  { label: 'Butter', value: 'butter' },
  { label: 'Egg', value: 'egg' },
  { label: 'Milk', value: 'milk' },
  { label: 'Chicken Breast', value: 'chicken-breast' },
  { label: 'Ground Beef', value: 'ground-beef' },
  { label: 'Ground Lamb', value: 'ground-lamb' },
  { label: 'Rice', value: 'rice' },
  { label: 'Lemon', value: 'lemon' },
  { label: 'Fresh Basil', value: 'fresh-basil' },
  { label: 'Oregano', value: 'oregano' },
  { label: 'Cumin', value: 'cumin' },
  { label: 'Paprika', value: 'paprika' },
  { label: 'Red Pepper Flakes', value: 'red-pepper-flakes' },
  { label: 'Yogurt', value: 'yogurt' },
  { label: 'Cheese', value: 'cheese' },
  { label: 'Potato', value: 'potato' },
  { label: 'Carrot', value: 'carrot' },
  { label: 'Bell Pepper', value: 'bell-pepper' },
  { label: 'Chickpeas', value: 'chickpeas' },
  { label: 'Red Lentils', value: 'red-lentils' },
  { label: 'Parsley', value: 'parsley' },
  { label: 'Cilantro', value: 'cilantro' },
  { label: 'Ginger', value: 'ginger' },
  { label: 'Soy Sauce', value: 'soy-sauce' },
  { label: 'Tomato Paste', value: 'tomato-paste' },
  { label: 'Honey', value: 'honey' },
  { label: 'Cinnamon', value: 'cinnamon' },
];

export const SAMPLE_TOOLS = [
  { label: 'Whisk', value: 'whisk' },
  { label: "Chef's Knife", value: 'chefs-knife' },
  { label: 'Mixing Bowl', value: 'mixing-bowl' },
  { label: 'Mortar & Pestle', value: 'mortar-pestle' },
  { label: 'Wooden Spoon', value: 'wooden-spoon' },
  { label: 'Blender', value: 'blender' },
  { label: 'Pasta Machine', value: 'pasta-machine' },
  { label: 'Cast Iron Pan', value: 'cast-iron-pan' },
  { label: 'Oven', value: 'oven' },
  { label: 'Pot', value: 'pot' },
  { label: 'Cutting Board', value: 'cutting-board' },
  { label: 'Rolling Pin', value: 'rolling-pin' },
  { label: 'Baking Sheet', value: 'baking-sheet' },
  { label: 'Colander', value: 'colander' },
  { label: 'Tongs', value: 'tongs' },
  { label: 'Grater', value: 'grater' },
  { label: 'Skewers', value: 'skewers' },
  { label: 'Charcoal Grill', value: 'charcoal-grill' },
];

export const QUICK_ADD_TOOLS = [
  'whisk', 'chefs-knife', 'mixing-bowl', 'mortar-pestle',
  'wooden-spoon', 'blender', 'pasta-machine',
];

export const UNIT_OPTIONS: { label: string; value: MeasurementUnit }[] = [
  { label: 'grams', value: 'g' },
  { label: 'kilograms', value: 'kg' },
  { label: 'milliliters', value: 'ml' },
  { label: 'liters', value: 'L' },
  { label: 'cups', value: 'cup' },
  { label: 'tablespoons', value: 'tbsp' },
  { label: 'teaspoons', value: 'tsp' },
  { label: 'pieces', value: 'piece' },
  { label: 'pinch', value: 'pinch' },
  { label: 'ounces', value: 'oz' },
  { label: 'pounds', value: 'lb' },
];
