import type { DietaryTag, AllergenTag } from '../types/common';

export const COUNTRIES = [
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'India', value: 'India' },
  { label: 'Japan', value: 'Japan' },
  { label: 'China', value: 'China' },
  { label: 'France', value: 'France' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'South Korea', value: 'South Korea' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Iran', value: 'Iran' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'Syria', value: 'Syria' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
];

export const GENRE_OPTIONS = [
  { label: 'Soup', value: '1' },
  { label: 'Kebap', value: '2' },
  { label: 'Pasta', value: '3' },
  { label: 'Salad', value: '4' },
  { label: 'Dessert', value: '5' },
  { label: 'Pastry', value: '6' },
  { label: 'Stew', value: '7' },
  { label: 'Rice Dish', value: '8' },
  { label: 'Meze', value: '9' },
  { label: 'Bread', value: '10' },
  { label: 'Seafood', value: '11' },
  { label: 'Wrap', value: '12' },
  { label: 'Beverage', value: '13' },
  { label: 'Curry', value: '14' },
  { label: 'Dumpling', value: '15' },
];

export const VARIETY_OPTIONS: Record<string, { label: string; value: string }[]> = {
  '1': [
    { label: 'Mercimek Çorbası', value: '101' },
    { label: 'Tarhana Çorbası', value: '102' },
    { label: 'Ezogelin Çorbası', value: '103' },
    { label: 'Minestrone', value: '104' },
    { label: 'Tom Yum', value: '105' },
    { label: 'Miso Soup', value: '106' },
    { label: 'French Onion Soup', value: '107' },
    { label: 'Gazpacho', value: '108' },
  ],
  '2': [
    { label: 'Adana Kebap', value: '201' },
    { label: 'Urfa Kebap', value: '202' },
    { label: 'İskender Kebap', value: '203' },
    { label: 'Şiş Kebap', value: '204' },
    { label: 'Döner Kebap', value: '205' },
    { label: 'Beyti Kebap', value: '206' },
    { label: 'Cağ Kebap', value: '207' },
    { label: 'Testi Kebap', value: '208' },
  ],
  '3': [
    { label: 'Tagliatelle al Ragù', value: '301' },
    { label: 'Spaghetti Carbonara', value: '302' },
    { label: 'Penne Arrabbiata', value: '303' },
    { label: 'Mantı', value: '304' },
    { label: 'Pad Thai', value: '305' },
    { label: 'Japchae', value: '306' },
  ],
  '4': [
    { label: 'Çoban Salatası', value: '401' },
    { label: 'Greek Salad', value: '402' },
    { label: 'Tabbouleh', value: '403' },
    { label: 'Caesar Salad', value: '404' },
    { label: 'Fattoush', value: '405' },
  ],
  '5': [
    { label: 'Baklava', value: '501' },
    { label: 'Künefe', value: '502' },
    { label: 'Tiramisu', value: '503' },
    { label: 'Mochi', value: '504' },
    { label: 'Sütlaç', value: '505' },
    { label: 'Churros', value: '506' },
    { label: 'Gulab Jamun', value: '507' },
  ],
  '6': [
    { label: 'Börek', value: '601' },
    { label: 'Simit', value: '602' },
    { label: 'Croissant', value: '603' },
    { label: 'Empanada', value: '604' },
    { label: 'Samosa', value: '605' },
    { label: 'Pide', value: '606' },
  ],
  '7': [
    { label: 'Güveç', value: '701' },
    { label: 'Tagine', value: '702' },
    { label: 'Ratatouille', value: '703' },
    { label: 'Nikujaga', value: '704' },
  ],
  '8': [
    { label: 'Pilav', value: '801' },
    { label: 'Biryani', value: '802' },
    { label: 'Risotto', value: '803' },
    { label: 'Paella', value: '804' },
    { label: 'Nasi Goreng', value: '805' },
  ],
  '9': [
    { label: 'Hummus', value: '901' },
    { label: 'Baba Ganoush', value: '902' },
    { label: 'Cacık', value: '903' },
    { label: 'Dolma', value: '904' },
    { label: 'Sigara Böreği', value: '905' },
  ],
  '10': [
    { label: 'Naan', value: '1001' },
    { label: 'Focaccia', value: '1002' },
    { label: 'Lavash', value: '1003' },
    { label: 'Pita', value: '1004' },
  ],
  '11': [
    { label: 'Sushi', value: '1101' },
    { label: 'Ceviche', value: '1102' },
    { label: 'Fish and Chips', value: '1103' },
    { label: 'Midye Dolma', value: '1104' },
  ],
  '12': [
    { label: 'Dürüm', value: '1201' },
    { label: 'Burrito', value: '1202' },
    { label: 'Gözleme', value: '1203' },
    { label: 'Spring Roll', value: '1204' },
  ],
  '13': [
    { label: 'Turkish Tea', value: '1301' },
    { label: 'Ayran', value: '1302' },
    { label: 'Turkish Coffee', value: '1303' },
    { label: 'Şalgam', value: '1304' },
    { label: 'Lassi', value: '1305' },
  ],
  '14': [
    { label: 'Tikka Masala', value: '1401' },
    { label: 'Green Curry', value: '1402' },
    { label: 'Rendang', value: '1403' },
    { label: 'Massaman Curry', value: '1404' },
  ],
  '15': [
    { label: 'Gyoza', value: '1501' },
    { label: 'Pierogi', value: '1502' },
    { label: 'Khinkali', value: '1503' },
    { label: 'Ravioli', value: '1504' },
  ],
};

export const DIETARY_TAG_OPTIONS: { label: string; value: DietaryTag }[] = [
  { label: 'Vegan', value: 'VEGAN' },
  { label: 'Vegetarian', value: 'VEGETARIAN' },
  { label: 'Halal', value: 'HALAL' },
  { label: 'Kosher', value: 'KOSHER' },
  { label: 'Gluten-Free', value: 'GLUTEN_FREE' },
];

export const ALLERGEN_TAG_OPTIONS: { label: string; value: AllergenTag }[] = [
  { label: 'Peanuts', value: 'PEANUTS' },
  { label: 'Dairy', value: 'DAIRY' },
  { label: 'Shellfish', value: 'SHELLFISH' },
  { label: 'Gluten', value: 'GLUTEN' },
  { label: 'Tree Nuts', value: 'TREE_NUTS' },
];
