name: Task
description: General work item for development, documentation, or setup
title: "[TASK] "
labels: ["task"]

body:
  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: "Write the task clearly (e.g., create a Wiki page, implement an API, fix deployment)."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Notes (Optional)
      description: Why is this needed? Any links or references?
      placeholder: "Add context, links, screenshots, or related issues (optional)."

  - type: textarea
    id: done_criteria
    attributes:
      label: Done Criteria
      description: How do we know this task is finished?
      placeholder: |
        - Deliverable exists (page/code/config/etc.)
        - Works as intended / links work (if applicable)
        - Reviewed by a teammate (if needed)
    validations:
      required: true
